In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
df=pd.read_csv("../spotify_data clean.csv")
df

,track_id,track_name,track_number,track_popularity,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type,track_duration_min
0,3EJS5LyekDim1Tf5rBFmZl,Trippy Mane (ft. Project Pat),4,0,True,Diplo,77,2812821,moombahton,5QRFnGnBeMGePBKF2xTz5z,"d00mscrvll, Vol. 1",2025-10-31,9,album,1.55
1,1oQW6G2ZiwMuHqlPpP27DB,OMG!,1,0,True,Yelawolf,64,2363438,"country hip hop, southern hip hop",4SUmmwnv0xTjRcLdjczGg2,OMG!,2025-10-31,1,single,3.07
2,7mdkjzoIYlf1rx9EtBpGmU,Hard 2 Find,1,4,True,Riff Raff,48,193302,NaN,3E3zEAL8gUYWaLYB9L7gbp,Hard 2 Find,2025-10-31,1,single,2.55
3,67rW0Zl7oB3qEpD5YWWE5w,Still Get Like That (ft. Project Pat & Starrah),8,30,True,Diplo,77,2813710,moombahton,5QRFnGnBeMGePBKF2xTz5z,"d00mscrvll, Vol. 1",2025-10-31,9,album,1.69
4,15xptTfRBrjsppW0INUZjf,ride me like a harley,2,0,True,Rumelis,48,8682,dark r&b,06FDIpSHYmZAZoyuYtc7kd,come closer / ride me like a harley,2025-10-30,2,single,2.39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8577,0AQquaENerGps8BQmbPw14,Big Iron,1,71,False,Marty Robbins,60,626733,"classic country, outlaw country",3kQpBS26lAj0A0VGl1snRl,Gunfighter Ballads And Trail Songs,1959-06-30,15,album,3.92
8578,4f8hBeMXMvssn6HtFAtblo,El Paso,10,64,False,Marty Robbins,61,626733,"classic country, outlaw country",3kQpBS26lAj0A0VGl1snRl,Gunfighter Ballads And Trail Songs,1959-06-30,15,album,4.32
8579,0Vy7wsXNFrbNc6UTWoScnM,Over the Rainbow,5,8,False,The Mystics,27,18184,doo-wop,2ifB9Xjp9DdpqLlYlY60QW,Presenting The Mystics,1959-02-11,9,compilation,2.28
8580,760clbeDBWmBsBLbszWuNZ,I'm A Man,2,55,False,Bo Diddley,44,333376,"blues, classic blues, rock and roll, rockabilly",1cbtDEwxCjMhglb49OgNBR,Bo Diddley,1958-01-01,12,album,2.74
8581,61GEP8lryEfcuEgBMbRmNi,Alone And Forsaken,11,45,False,Hank Williams,55,1067339,"classic country, honky tonk, traditional count...",3cusZESjkIDnDXyQwbpSsT,Moanin' The Blues (Expanded Edition),1952-09-12,12,album,2.02

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8582 entries, 0 to 8581
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   track_id            8582 non-null   object
 1   track_name          8582 non-null   object
 2   track_number        8582 non-null   int64
 3   track_popularity    8582 non-null   int64
 4   explicit            8582 non-null   bool
 5   artist_name         8579 non-null   object
 6   artist_popularity   8582 non-null   int64
 7   artist_followers    8582 non-null   int64
 8   artist_genres       5221 non-null   object
 9   album_id            8582 non-null   object
 10  album_name          8582 non-null   object
 11  album_release_date  8582 non-null   object
 12  album_total_tracks  8582 non-null   int64
 13  album_type          8582 non-null   object
 14  track_duration_min  8582 non-null   float64
dtypes: bool(1), float64(1), int64(5), object(8)
memory usage: 947.2+ KB

In [22]:
df.describe()

,track_number,track_popularity,artist_popularity,artist_followers,album_total_tracks,track_duration_min
count,8582.000000,8582.000000,8582.000000,8.582000e+03,8582.000000,8582.000000
mean,5.772547,52.356211,69.730016,2.403472e+07,13.789443,3.492805
std,6.052792,23.816076,19.645979,3.803180e+07,11.887131,1.057970
min,1.000000,0.000000,0.000000,0.000000e+00,1.000000,0.070000
25%,1.000000,39.000000,60.000000,4.623200e+05,6.000000,2.880000
50%,4.000000,58.000000,74.000000,6.105547e+06,13.000000,3.445000
75%,9.000000,71.000000,84.000000,2.725255e+07,17.000000,3.990000
max,102.000000,99.000000,100.000000,1.455421e+08,181.000000,13.510000

In [23]:
df.isnull().sum()

track_id                 0
track_name               0
track_number             0
track_popularity         0
explicit                 0
artist_name              3
artist_popularity        0
artist_followers         0
artist_genres         3361
album_id                 0
album_name               0
album_release_date       0
album_total_tracks       0
album_type               0
track_duration_min       0
dtype: int64

In [24]:
print(df.columns)

Index(['track_id', 'track_name', 'track_number', 'track_popularity',
       'explicit', 'artist_name', 'artist_popularity', 'artist_followers',
       'artist_genres', 'album_id', 'album_name', 'album_release_date',
       'album_total_tracks', 'album_type', 'track_duration_min'],
      dtype='object')

In [25]:
df["popular"]=df["track_popularity"].apply(lambda x:1 if x>=60 else 0)

In [26]:
from sklearn.preprocessing import LabelEncoder, StandardScaler
le=LabelEncoder()
df["explicit"]=le.fit_transform(df["explicit"])
df["album_type"]=le.fit_transform(df["album_type"])

In [57]:
features=[
    "artist_popularity",
    "artist_followers",
    "track_duration_min",
    "album_total_tracks",
    "explicit",
    "album_type"
]
x=df[features]
y=df["popular"]

In [58]:
df[features].describe()

,artist_popularity,artist_followers,track_duration_min,album_total_tracks,explicit,album_type
count,8582.000000,8.582000e+03,8582.000000,8582.000000,8582.000000,8582.000000
mean,69.730016,2.403472e+07,3.492805,13.789443,0.250291,0.576206
std,19.645979,3.803180e+07,1.057970,11.887131,0.433206,0.872588
min,0.000000,0.000000e+00,0.070000,1.000000,0.000000,0.000000
25%,60.000000,4.623200e+05,2.880000,6.000000,0.000000,0.000000
50%,74.000000,6.105547e+06,3.445000,13.000000,0.000000,0.000000
75%,84.000000,2.725255e+07,3.990000,17.000000,1.000000,2.000000
max,100.000000,1.455421e+08,13.510000,181.000000,1.000000,2.000000

In [59]:
df[features].isnull().sum()

artist_popularity     0
artist_followers      0
track_duration_min    0
album_total_tracks    0
explicit              0
album_type            0
dtype: int64

In [60]:
Scaler=StandardScaler()
x=Scaler.fit_transform(x)

In [61]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8, random_state=42)

In [62]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr

LogisticRegression()

In [63]:
lr.fit(x_train,y_train)

LogisticRegression()

In [64]:
y_pred=lr.predict(x_test)
y_pred

array([0, 1, 1, ..., 1, 0, 0], shape=(1717,))

In [65]:
from sklearn.metrics import accuracy_score, classification_report
print("Accuracy :",accuracy_score(y_test,y_pred))

Accuracy : 0.7169481654047758

In [66]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.77      0.67      0.71       912
           1       0.67      0.78      0.72       805

    accuracy                           0.72      1717
   macro avg       0.72      0.72      0.72      1717
weighted avg       0.72      0.72      0.72      1717

In [67]:
from sklearn.svm import SVC
svm =SVC()
svm

SVC()

In [68]:
svm.fit(x_train,y_train)

SVC()

In [69]:
y_pred1=svm.predict(x_test)
y_pred1

array([1, 1, 1, ..., 1, 0, 0], shape=(1717,))

In [70]:
print("Accuracy :", accuracy_score(y_test,y_pred1))

Accuracy : 0.7198602213162493

In [71]:
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.83      0.59      0.69       912
           1       0.65      0.86      0.74       805

    accuracy                           0.72      1717
   macro avg       0.74      0.73      0.72      1717
weighted avg       0.75      0.72      0.72      1717

In [72]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf

RandomForestClassifier()

In [73]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [74]:
y_pred2=rf.predict(x_test)
y_pred2

array([0, 1, 1, ..., 1, 0, 0], shape=(1717,))

In [75]:
print("Accuracy :", accuracy_score(y_test,y_pred2))

Accuracy : 0.7530576587070472

In [76]:
print(classification_report(y_test,y_pred2))

              precision    recall  f1-score   support

           0       0.77      0.77      0.77       912
           1       0.74      0.74      0.74       805

    accuracy                           0.75      1717
   macro avg       0.75      0.75      0.75      1717
weighted avg       0.75      0.75      0.75      1717

In [77]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model=Sequential([
    Dense(32,activation='relu',input_shape=(x_train.shape[1],)),
    Dense(16,activation='relu'),
    Dense(1,activation='sigmoid')
])

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=['accuracy']
)
model.fit(
    x_train,y_train,epochs=20,batch_size=32,validation_split=0.2
)

Epoch 1/20

C:\Users\Rohan Landge\AppData\Roaming\Python\Python313\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

172/172 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6238 - loss: 0.6219 - val_accuracy: 0.6854 - val_loss: 0.5765
Epoch 2/20
172/172 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7068 - loss: 0.5453 - val_accuracy: 0.7007 - val_loss: 0.5563
Epoch 3/20
172/172 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7130 - loss: 0.5342 - val_accuracy: 0.7116 - val_loss: 0.5465
Epoch 4/20
172/172 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7156 - loss: 0.5293 - val_accuracy: 0.7130 - val_loss: 0.5439
Epoch 5/20
172/172 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7170 - loss: 0.5267 - val_accuracy: 0.7138 - val_loss: 0.5425
Epoch 6/20
172/172 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7165 - loss: 0.5245 - val_accuracy: 0.7094 - val_loss: 0.5410
Epoch 7/20
172/172 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7152 - loss: 0.5238 - val_accuracy: 0.7094 - val_loss: 0.5400
Epoch 8/20
172/172 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7170 - loss: 0.5218 - val_accuracy: 0.7072 - val_loss: 0.5391
Epoch 9/20
172/172 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7192 - loss: 0.5210 - val_accuracy: 0.7079 - val_loss: 0.5387
Epoch 10/20
172/172 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7194 - loss: 0.5205 - val_accuracy: 0.7138 - val_loss: 0.5404
Epoch 11/20
172/172 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7181 - loss: 0.5191 - val_accuracy: 0.7116 - val_loss: 0.5380
Epoch 12/20
172/172 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7192 - loss: 0.5184 - val_accuracy: 0.7072 - val_loss: 0.5367
Epoch 13/20
172/172 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7198 - loss: 0.5179 - val_accuracy: 0.7079 - val_loss: 0.5373
Epoch 14/20
172/172 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7194 - loss: 0.5164 - val_accuracy: 0.7116 - val_loss: 0.5359
Epoch 15/20
172/172 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7203 - loss: 0.5158 - val_accuracy: 0.7101 - val_loss: 0.5357
Epoch 16/20
172/172 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7176 - loss: 0.5158 - val_accuracy: 0.7130 - val_loss: 0.5359
Epoch 17/20
172/172 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7210 - loss: 0.5151 - val_accuracy: 0.7130 - val_loss: 0.5367
Epoch 18/20
172/172 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7212 - loss: 0.5145 - val_accuracy: 0.7101 - val_loss: 0.5359
Epoch 19/20
172/172 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7190 - loss: 0.5146 - val_accuracy: 0.7109 - val_loss: 0.5345
Epoch 20/20
172/172 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7238 - loss: 0.5145 - val_accuracy: 0.7152 - val_loss: 0.5342

In [78]:
loss,acc=model.evaluate(x_test,y_test)
print("Tensorflow Accuracy :",acc)

54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7164 - loss: 0.5293
Tensorflow Accuracy : 0.7163657546043396

In [79]:
artist_popularity = float(input("Artist popularity :"))
artist_followers=float(input("Artist Followers :"))
duration=float(input("Track duration(min) :"))
album_tracks=int(input("Album total Tracks:"))
explicit=int(input("explicit (0=No,1=Yes):"))
album_type=int(input("Album type (encoded): "))

sample=[[artist_popularity,artist_followers,duration,album_tracks,explicit,album_type]]

sample=Scaler.transform(sample)

prediction=rf.predict(sample)

if prediction[0]==1:
    print("Prediction: Popular Track")
else:
    print("Prediction : Not Popular")

Artist popularity : 99
Artist Followers : 76899000
Track duration(min) : 4
Album total Tracks: 9
explicit (0=No,1=Yes): 0
Album type (encoded):  4

Prediction: Popular Track

C:\Users\Rohan Landge\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(