In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv(r"C:\Users\Rohan Landge\Downloads\Twitter_Data.csv\Twitter_Data.csv")
df

                                               clean_text  category
0       when modi promised “minimum government maximum...      -1.0
1       talk all the nonsense and continue all the dra...       0.0
2       what did just say vote for modi  welcome bjp t...       1.0
3       asking his supporters prefix chowkidar their n...       1.0
4       answer who among these the most powerful world...       1.0
...                                                   ...       ...
162975  why these 456 crores paid neerav modi not reco...      -1.0
162976  dear rss terrorist payal gawar what about modi...      -1.0
162977  did you cover her interaction forum where she ...       0.0
162978  there big project came into india modi dream p...       0.0
162979  have you ever listen about like gurukul where ...       1.0

[162980 rows x 2 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 162980 entries, 0 to 162979
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   clean_text  162976 non-null  object
 1   category    162973 non-null  float64
dtypes: float64(1), object(1)
memory usage: 2.5+ MB

In [5]:
df.describe()

            category
count  162973.000000
mean        0.225436
std         0.781279
min        -1.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         1.000000

In [6]:
df.columns

Index(['clean_text', 'category'], dtype='object')

In [8]:
df.isnull().sum

clean_text    4
category      7
dtype: int64

In [9]:
df.dropna(inplace=True)

In [10]:
df.isnull().sum()

clean_text    0
category      0
dtype: int64

In [11]:
df["category"].value_counts()

category
 1.0    72249
 0.0    55211
-1.0    35509
Name: count, dtype: int64

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer()
x=vectorizer.fit_transform(df["clean_text"])
y=df["category"]

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=42)

In [14]:
from sklearn.naive_bayes import MultinomialNB
mb=MultinomialNB()
mb

MultinomialNB()

In [15]:
mb.fit(x_train,y_train)

MultinomialNB()

In [16]:
y_pred=mb.predict(x_test)
y_pred

array([1., 1., 1., ..., 1., 0., 1.], shape=(32594,))

In [17]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print("Accuracy of Multinomial Model :",accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy of Multinomial Model : 0.5673436828864208
              precision    recall  f1-score   support

        -1.0       0.95      0.10      0.18      7152
         0.0       0.91      0.32      0.48     11067
         1.0       0.51      0.99      0.67     14375

    accuracy                           0.57     32594
   macro avg       0.79      0.47      0.44     32594
weighted avg       0.74      0.57      0.50     32594