In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [4]:
df=pd.read_csv("../spam.csv",encoding="latin-1")
df

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [5]:
df.isnull().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

In [6]:
df.columns

Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')

In [7]:
df=df.drop(columns=["Unnamed: 2","Unnamed: 3","Unnamed: 4"])

In [8]:
df.columns

Index(['v1', 'v2'], dtype='object')

In [9]:
df.columns=["label","text"]

In [10]:
df.head()

  label                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [11]:
df["label"]=df["label"].map({"ham":0,"spam":1})

In [12]:
print(df.shape)

(5572, 2)

In [13]:
def clean_text(text):
    text=text.lower()
    text=re.sub(r'[^a-zA-Z]',' ',text)
    return text

In [14]:
df["clean_text"]=df["text"].apply(clean_text)

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer(stop_words='english')
x=vectorizer.fit_transform(df["clean_text"])
y=df["label"]

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [18]:
from sklearn.naive_bayes import MultinomialNB
nb=MultinomialNB()
nb

MultinomialNB()

In [19]:
nb.fit(x_train,y_train)

MultinomialNB()

In [20]:
y_pred=nb.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 1], shape=(1115,))

In [21]:
from sklearn.metrics import accuracy_score,classification_report
print("Accuracy :",accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy : 0.967713004484305
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       965
           1       1.00      0.76      0.86       150

    accuracy                           0.97      1115
   macro avg       0.98      0.88      0.92      1115
weighted avg       0.97      0.97      0.97      1115

In [22]:
user_msg=input("Enter SMS or Email :")
msg=clean_text(user_msg)
msg_vec=vectorizer.transform([msg])
prediction=nb.predict(msg_vec)
if prediction[0]==1:
    print("Prediction:Spam Message")
else:
    print("Prediction: Ham (Not Spam)")

Enter SMS or Email : WIN a free iPhone now!!! Click here to claim your prize

Prediction:Spam Message